name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using Ollama API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OLLAMA_SERVER_URL:
    description: "Ollama server URL."
    required: true
  GITHUB_EVENT_PATH:
    description: "Path to the GitHub event JSON file."
    required: true
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "index.js"
branding:
  icon: "aperture"
  color: "green"
